### PR TITLE
Stringifies log messages if objects

### PR DESCRIPTION
**Pull request by jungeunyoon**
The other modules' rise-common-electron dependency release versions will have to be changed and then I'll manually test.

### CODE REVIEW

**Comment by stulees** [comment]
@jungeunyoon Can you provide an example in one of the modules where `userFriendlyMessage` is an object?

**Comment by santiagonoguez** [comment]
@stulees @jungeunyoon I think display control is one of such modules, as it has some logs with that [object Object] format

**Comment by jungeunyoon** [comment]
@stulees I actually also noticed [this](https://github.com/Rise-Vision/rise-common-electron/blob/master/logger.js#L111) as well. `evt` and `detail` params should be switched, yeah?

**Comment by santiagonoguez** [comment]
I guess evt should not be sent, and detail should be first argument.

**Comment by santiagonoguez** [comment]
userFriendlyMessage not there, so "" should be sent maybe

**Comment by stulees** [comment]
@jungeunyoon Yes that looks like the bug. I don't think `userFriendlyMessage` was ever expected to be an object, so I don't think the changes in this PR fix the issue. @santiagonoguez

**Comment by jungeunyoon** [comment]
@stulees good catch overall, thanks!

**Pull request merged**
